/**
 * POST /api/analytics-insights
 *
 * Accepts raw analytics data (traffic, conversions, audience, content) and
 * returns structured, actionable marketing insights generated by Claude Opus.
 *
 * Body:
 *   {
 *     analyticsData: {
 *       trafficSources?: Record<string, number>;
 *       conversionRates?: Record<string, number>;
 *       topContent?: Array<{ title: string; views: number; conversions: number }>;
 *       audienceSegments?: Array<{ segment: string; sessions: number; conversionRate: number }>;
 *       dateRange?: string;
 *     }
 *   }
 *
 * Response:
 *   {
 *     insights: {
 *       bestTrafficSource: { source: string; reasoning: string };
 *       highestConvertingAudience: { segment: string; reasoning: string };
 *       topPerformingContent: { title: string; reasoning: string };
 *       quickWins: string[];
 *       summary: string;
 *     }
 *   }
 */

import Anthropic from "@anthropic-ai/sdk";
import type { NextApiRequest, NextApiResponse } from "next";

const anthropic = new Anthropic({ apiKey: process.env.CLAUDE_API_KEY });

interface AnalyticsInsightsRequest {
  analyticsData: {
    trafficSources?: Record<string, number>;
    conversionRates?: Record<string, number>;
    topContent?: Array<{ title: string; views: number; conversions: number }>;
    audienceSegments?: Array<{
      segment: string;
      sessions: number;
      conversionRate: number;
    }>;
    dateRange?: string;
  };
}

interface AnalyticsInsightsResponse {
  insights: {
    bestTrafficSource: { source: string; reasoning: string };
    highestConvertingAudience: { segment: string; reasoning: string };
    topPerformingContent: { title: string; reasoning: string };
    quickWins: string[];
    summary: string;
  };
  error?: string;
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<AnalyticsInsightsResponse>
) {
  if (req.method !== "POST") {
    return res
      .status(405)
      .json({ insights: null as never, error: "Method not allowed" });
  }

  const { analyticsData } = req.body as AnalyticsInsightsRequest;

  if (!analyticsData || typeof analyticsData !== "object") {
    return res
      .status(400)
      .json({ insights: null as never, error: "analyticsData is required" });
  }

  const prompt = `You are a senior marketing data analyst. Analyze the following analytics data and return structured, actionable insights.

DATA:
${JSON.stringify(analyticsData, null, 2)}

Return ONLY valid JSON with no markdown fences, exactly this shape:
{
  "bestTrafficSource": {
    "source": "<source name>",
    "reasoning": "<1–2 sentences on why this source is best>"
  },
  "highestConvertingAudience": {
    "segment": "<segment name>",
    "reasoning": "<1–2 sentences on why this segment converts best>"
  },
  "topPerformingContent": {
    "title": "<content title>",
    "reasoning": "<1–2 sentences on what makes it top performing>"
  },
  "quickWins": [
    "<actionable tactic 1 based on the data>",
    "<actionable tactic 2>",
    "<actionable tactic 3>"
  ],
  "summary": "<2–3 sentence plain-English summary of the single biggest optimization opportunity>"
}

Rules:
- Every recommendation must be grounded in the provided data
- quickWins must be specific and actionable, not generic
- If a data category is missing, skip it gracefully rather than inventing numbers`;

  try {
    const response = await anthropic.messages.create({
      model: "claude-opus-4-6",
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    });

    const rawText = response.content
      .filter((b) => b.type === "text")
      .map((b) => (b as { type: "text"; text: string }).text)
      .join("");

    const cleaned = rawText
      .replace(/^```(?:json)?\s*/i, "")
      .replace(/\s*```\s*$/, "")
      .trim();

    const insights = JSON.parse(cleaned);
    return res.status(200).json({ insights });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Analysis failed";
    return res.status(500).json({ insights: null as never, error: message });
  }
}
